#1223 - fixed issue with start and end vlan params when adding new ACL
GlobalNOC/OESS pull request #1244
Opened 2021-04-05 13:50 UTC by khood5

#1223 - Fix for wrong params in adding ACL

2021-04-13 17:14 UTC, ajragusa approved these changes

2021-04-14 14:54 UTC, jonstout requested changes
Looks good, but this same issue also exists within the admin section. Could you fix this issue there as well?

2021-07-14 03:34 UTC, jonstout approved these changes

2021-07-14 03:36 UTC, jonstout commented
> Looks good, but this same issue also exists within the admin section. Could you fix this issue there as well?

My bad. This fixed both places. Good job. 👍

2021-07-14 03:36 UTC, merged