1274 create node interfaces page
GlobalNOC/OESS pull request #1287
Opened 2021-06-28 15:15 UTC by bensiefers

Adds an interface page to the new admin UI. Shows all the interfaces for a node. Fixes #1274.

2021-06-28 18:44 UTC, bensiefers commented
Recent commits do two notable things.
- it adds the role property to the interface model so that it can be accessed for the interface page
- it adds a function called `get_node_interfaces` that gets interfaces by node_id.
  -  the function is needed as the data.cgi equivalent doesn't get a holistic view of the interface model.

2021-09-30 19:47 UTC, jonstout requested changes

2021-09-30 19:47 UTC, jonstout commented on frontend/webservice/interface.cgi
> +    }
I'm guessing you meant to pass workgroup_id into get_interfaces if it was defined? You really don't need to; If an arg is undef it won't be filtered on, so you can go ahead and pass node_id and workgroup_id into get_interfaces regardless.

2021-09-30 19:47 UTC, jonstout commented on frontend/webservice/interface.cgi
> +                                  required => 1,
node_id should be an optional param for this web service method.

2021-12-08 17:20 UTC, merged